version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  url-shortener:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_FILE: /app/config/config.yaml
    depends_on:
      - redis
